### PR TITLE
fix socket.kickOut() v17

### LINKED ISSUE #49: socket.kickOut fails
`socket.kickOut()` with no arguments provided fails to unsubscribe the socket from channels.  

```js
await socket.exchange.invokePublish('foo', 1)
socket.kickOut()
await sleep(300)
await socket.exchange.invokePublish('foo', 2)
```
Client receives `#kickOut` but still receives the second message after that.  
`socketcluster-server` v14 and v17 exhibit the same behavior.  

Slightly related https://github.com/SocketCluster/socketcluster-server/issues/29

### PR DESCRIPTION
**Pull request by MegaGM**
closes https://github.com/SocketCluster/socketcluster-server/issues/49

### CODE REVIEW

File: serversocket.js [hunk 1]
```diff
@@ -1427,10 +1427,19 @@ AGServerSocket.prototype.deauthenticate = async function (options) {
...
+    channels = Object.keys(this.channelSubscriptions);
+  }
+  if (!Array.isArray(channels)) {
+    channels = [channel];
+  }
+  for (const channelName of channels) {
+    delete this.channelSubscriptions[channelName];
+    this.channelSubscriptionsCount--;
+    this.transmit('#kickOut', {channel: channelName, message});
+    this.server.brokerEngine.unsubscribeSocket(this, channelName);
```
Comment (jondubois) [inline serversocket.js:1441]: Ideally, the kickOut method should be async and it should await on the `this.server.brokerEngine.unsubscribeSocket(this, channelName);` line. In this case, we would need to use `await Promise.all(...)` instead of the for loop so that channels can be processed in parallel.

Although it doesn't matter for the default brokerEngine since the unsubscribeSocket method is async.
It's in case the user provides a custom brokerEngine - Then it's possible that the unsubscribe could have a delay (not be instant like the default).

**Review by jondubois — CHANGES_REQUESTED** [review]
I proposed a change to account for a very specific edge case.
Let me know if you have any thoughts about it. I was thinking it's almost not worth handling but it shouldn't be too difficult to do so.

File: serversocket.js (hunk 1 above)
Comment (MegaGM) [reply serversocket.js:1441]: Good point. I'll try to implement that.

Comment (MegaGM) [reply serversocket.js]: Custom brokers could not only introduce a delay, but also could throw something.  
I've simulated a error within `AGSimpleBroker.unsubscribeClient` and have found out that it causes crashes on `socket._destroy`, because unlike `socket._subscribeSocket`, `socket._unsubscribe` doesn't account for possibility of broker errors.

I guess it won't hurt to also emit these two events on `socket.kickOut` too:  
socket 'unsubscribe'  
agServer 'unsubscription'

**Comment by MegaGM** [comment]
TODO
- [ ] update typings https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/socketcluster-server/v15/serversocket.d.ts#L192
- [ ] update docs

File: serversocket.js (hunk 1 above)
Comment (jondubois) [reply serversocket.js]: Nice! I'll try it out and aim to get this merged ASAP.
